module.exports = {
  shortcode: '41444',
  keyword: 'Location123',
  type: 'Fundraising',
  volunteer_fundraiser: null,
  team: '',
  alternative_team_id: '',
  transaction_date: '09/21/2017 22:25',
  donation_date: '09/21/2017 22:09',
  collected_amount: '$1.00',
  pledged_amount: '$1.00',
  processing_fee: null,
  fee_rate: null,
  cc_type: 'Visa',
  last_4: '1234',
  phone: '16178204019',
  first_name: 'John',
  last_name: 'Tester',
  street_address: '123 Fake Street',
  city: 'Los Angeles',
  state: 'CA',
  zip: '90007',
  email: 'john@crs-consulting.com',
  gender: null,
  billing_status: 'settled',
  billing_type: 'sale',
  donation: '12345678',
  transaction_id: '1234567',
  source: 'Paid via Mobile Web (Pledging)',
  form: 'Text To Donate (Donation)',
  form_payment_type: 'payment',
  form_name: 'Text To Donate',
  form_type: 'donation',
  form_id: '12345',
  fulfillment_calls: '0',
  fulfillment_texts: '0',
  donation_notes: '',
  account: 'NTW Integration',
  account_id: '7907',
  campaign_name: 'NTW Test Campaign',
  account_plan: 'Unknown',
  account_plan_price: '$0.00',
  frequency: 'One Time',
  anonymous: 'No',
  billing_transaction: 'abcde01f',
  billing_transaction_reference: '123456',
  billing_response_code: '1000',
  parent_name: '',
  payment_gateway: 'McBraintree',
  are_you_a_veteran: null,
};

